import { toHex } from "@midnight-ntwrk/midnight-js-utils";

/**
 * Generates a buffer containing a series of randomly generated bytes.
 *
 * @param length The number of bytes to generate.
 * @returns A `Uint8Array` representing `length` randomly generated bytes.
 */
export const randomBytes = (length: number): Uint8Array => {
  const bytes = new Uint8Array(length);
  crypto.getRandomValues(bytes);
  return bytes;
};

/**
 * Generates a random hex-encoded public key.
 */
export const randomCoinPublicKeyHex = (): string => {
  return toHex(randomBytes(32));
}